### ISSUE TITLE
Failed to load deprecated vision dynamite module

### ISSUE THREAD

**Issue by Penknife0915** [CharlesMoreira1/lingshot#116]
After navigating to the field I want to translate, I get the following error:

Failed to load deprecated vision dynamite module.

**Comment by CharlesMoreira1** [comment]
> Depois de navegar até o campo que desejo traduzir, recebo o seguinte erro:
> 
> Falha ao carregar o módulo Vision Dynamite obsoleto.

Hi! Yesterday the API had a problem. 
Could you try now?
